system/modules/dashboard/controllers/WxbindingController.php
<?php

/**
 * WxBindingController.class.file
 *
 * @author gzhzh <gzhzh@ibos.com.cn>
 * @link http://www.ibos.com.cn/
 * @copyright Copyright &copy; 2012-2013 IBOS Inc
 */
/**
 * 微信企业号设置控制器
 *
 * @package application.modules.dashboard.controllers
 * @author gzhzh <gzhzh@ibos.com.cn>
 * @version $Id: WxBindingController.php 2052 2014-09-22 10:05:11Z gzhzh $
 */

namespace application\modules\dashboard\controllers;

use application\core\utils\Ibos;
use application\core\utils\WebSite;
use CJSON;

class WxbindingController extends WxController
{

    /**
     * 获取企业号绑定视图
     */
    public function actionIndex()
    {
        $unit = Ibos::app()->setting->get('setting/unit');
        $aeskey = Ibos::app()->setting->get('setting/aeskey');
        $params = array(
            'fullname' => $unit['fullname'],
            'shortname' => $unit['shortname'],
            'logo' => $unit['logourl'],
            'domain' => $unit['systemurl'],
            'aeskey' => $aeskey,
            'isBinding' => $this->isBinding,
        );
        $isLogin = $this->wxqyInfo['isLogin'];
        if (false === $isLogin) {
            $view = 'login';
        } else {
            $view = 'index';
            // 改为jsonp请求，避免双向curl阻塞
            // $res = WebSite::getInstance()->fetch('Api/Api/checkAccess', array(
            //     'domain' => $unit['systemurl'],
            //     'aeskey' => $aeskey,
            // ), 'post');
            // if (is_array($res)) {
            //     $isSuccess = false;
            //     $msg = $res['error'];
            // } else {
            //     $result = CJSON::decode($res);
            //     $isSuccess = $result['isSuccess'];
            //     $msg = $result['msg'];
            // }
            // $params['access'] = $isSuccess;
            // $params['msg'] = $msg;
        }
//        if (true === $this->isBinding) {
//            $params['wxlogo'] = $this->wxqyInfo['logo'];
//            $params['wxcorpid'] = $this->wxqyInfo['corpid'];
//            $params['wxname'] = $this->wxqyInfo['name'];
//            $params['mobile'] = $this->wxqyInfo['mobile'];
//            $params['app'] = $this->wxqyInfo['app'];
//            if (true === $isLogin) {
//                return $this->redirect($this->createUrl('wxsync/app'));
//            }
//        }
//        return $this->redirect($this->createUrl('wxsync/app'));
        return $this->render($view, $params);
    }

    public function actionCheckAccess()
    {
        $domain = Ibos::app()->getRequest()->getPost('domain');
        $aeskey = Ibos::app()->setting->get('setting/aeskey');
        $res = WebSite::getInstance()->fetch('Api/Api/checkAccess', array(
            'domain' => $domain,
            'aeskey' => $aeskey,
        ), 'post');
        $ajaxReturn = $this->ajaxReturnArray($res);
        return $this->ajaxReturn($ajaxReturn);
    }

    public function actionLogin()
    {
        $request = Ibos::app()->getRequest();
        $mobile = $request->getPost('mobile');
        $password = $request->getPost('password');
        $res = WebSite::getInstance()->fetch('Api/Api/login', array(
            'mobile' => $mobile,
            'password' => $password,
        ), 'post');
        $ajaxReturn = $this->ajaxReturnArray($res);
        if (true === $ajaxReturn['isSuccess']) {
            Ibos::app()->user->setState('param', array(
                'uid' => $ajaxReturn['data']['uid'],
                'wxqyInfo' => array('mobile' => $mobile)
            ));
        }
        return $this->ajaxReturn($ajaxReturn);
    }

    public function actionLogout()
    {
        Ibos::app()->user->setState('param', array());
        return $this->redirect($this->createUrl('wxbinding/index'));
    }

    public function actionRegister()
    {
        $request = Ibos::app()->getRequest();
        $mobile = $request->getPost('mobile');
        $password = $request->getPost('password');
        $username = $request->getPost('realname');
        $res = WebSite::getInstance()->fetch('Api/Api/register', array(
            'mobile' => $mobile,
            'password' => $password,
            'username' => $username,
        ), 'post');
        $ajaxReturn = $this->ajaxReturnArray($res);
        if (true === $ajaxReturn['isSuccess']) {
            Ibos::app()->user->setState('param', array(
                'uid' => $ajaxReturn['data']['uid'],
                'wxqyInfo' => array('mobile' => $mobile)
            ));
        }
        return $this->ajaxReturn($ajaxReturn);
    }

    public function actionSendCode()
    {
        $request = Ibos::app()->getRequest();
        $mobile = $request->getPost('mobile');
        $res = WebSite::getInstance()->fetch('Api/Api/sendCode', array(
            'mobile' => $mobile,
        ), 'post');
        $ajaxReturn = $this->ajaxReturnArray($res);
        return $this->ajaxReturn($ajaxReturn);
    }

    public function actionCheckCode()
    {
        $request = Ibos::app()->getRequest();
        $mobile = $request->getPost('mobile');
        $code = $request->getPost('verifyCode');
        $res = WebSite::getInstance()->fetch('Api/Api/checkCode', array(
            'mobile' => $mobile,
            'code' => $code,
        ), 'post');
        $ajaxReturn = $this->ajaxReturnArray($res);
        return $this->ajaxReturn($ajaxReturn);
    }

    public function actionCheckMobile()
    {
        $request = Ibos::app()->getRequest();
        $mobile = $request->getPost('mobile');
        $res = WebSite::getInstance()->fetch('Api/Api/checkMobile', array(
            'mobile' => $mobile,
        ), 'post');
        $ajaxReturn = $this->ajaxReturnArray($res);
        return $this->ajaxReturn($ajaxReturn);
    }

    private function ajaxReturnArray($res)
    {
        if (is_array($res)) {
            return array(
                'isSuccess' => false,
                'msg' => $res['error'],
            );
        } else {
            $result = CJSON::decode($res);
            return array(
                'isSuccess' => $result['isSuccess'],
                'msg' => isset($result['msg']) ? $result['msg'] : '',
                'data' => isset($result['data']) ? $result['data'] : array(),
            );
        }
    }

    public function actionLocationWx()
    {
        $request = Ibos::app()->request;
        $domain = $request->getPost('domain');
        $aeskey = Ibos::app()->setting->get('setting/aeskey');
        if (isset(Ibos::app()->user->param['uid'])) {
            //如果没有登录酷办公，就强制跳转到首页登录
            $uid = Ibos::app()->user->param['uid'];
        } else {
            Ibos::app()->user->setState('param', array());
            return $this->redirect($this->createUrl('wxbinding/index'));
        }
        $url = WebSite::getInstance()->build('Wxapi/Api/toWx', array(
            'state' => base64_encode(json_encode(array(
                'domain' => $domain,
                'uid' => $uid,
                'ibosuid' => Ibos::app()->user->uid,
                'aeskey' => $aeskey,
                'version' => strtolower(implode(',', array(ENGINE, VERSION, VERSION_TYPE)))
            )))
        ));
        $url .= '&' . rand(0, 999);
        return $this->ajaxReturn(array(
            'isSuccess' => true,
            'msg' => '',
            'data' => array(
                'url' => $url,
            ),
        ));
    }

}

system/modules/dashboard/views/wxbinding/index.php
<?php

use application\core\utils\Ibos;
use application\modules\dashboard\utils\Wx;

?>
<link href="<?php echo $this->getAssetUrl(); ?>/css/weixin.css" type="text/css" rel="stylesheet">
<div>
    <div class="ct">
        <div class="clearfix">
            <h1 class="mt"><?php echo $lang['Binding wechat and enjoy it']; ?></h1>
        </div>
        <div>
            <!-- 企业信息 start -->
            <div class="ctb">
                <h2 class="st"><?php echo $lang['Wechat binding'] ?></h2>
                <div class="co-banding-wrap">
                    <div class="box-shadow ibosoa-info clearfix">
                        <div class="company-logo mbs pull-left">
                            <img src="<?php echo !empty($logo) ? $logo : 'static/image/logo.png'; ?>"
                                 alt="<?php echo $shortname; ?>">
                            <div class="ibos-logo">
                                <i class="o-binding-ibos"></i>
                            </div>
                        </div>
                        <div class="company-info pull-left">
                            <p class="lhl t"><?php echo $fullname; ?></p>
                            <p class="lhl">系统URL : <?php echo $domain; ?></p>
                            <p class="lhl ellipsis"
                               title="AES KEY : 9Pcz3VcUe6kh-GEAgU3vL99rHUk5F7C-libcteUhQkYC72D8qf">AES KEY
                                : <?php echo $aeskey; ?></p>
                        </div>
                    </div>
                    <div class="wx-access-panel"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/template" id="access_tpl">
    <div class="wx-binding-check">
        <div class="wx-check-result">
            <i class="mbs <%= isSuccess ? 'o-result-tip' : 'o-failure-tip' %>"></i>
            <% if (isSuccess) { %>
                <p class="xcgn mbm">系统URL验证成功！</p>
                <p>接下来你可以使用该域名授权并安装套件应用</p>
            <% } else { %>
                <p class="xcr mbm">系统URL验证失败！</p>
                <p>请检查系统URL是否可被微信服务器访问，请填写正确URL验证并授权</p>
            <% } %>
        </div>
        <% if (isSuccess) { %>
            <div>
                <input type="hidden" class="dib span5" name="sysurl" value="<?php echo $domain; ?>"/>
            </div>
        <% } else { %>
            <div>
                <input type="text" class="dib span5" name="sysurl" value="<?php echo $domain; ?>"/>
                <button class="btn btn-primary mlm" data-action="bindWXCheck">验证</button>
            </div>
        <% } %>
    </div>
    <div class="wx-btn-group">
        <a class="wx-back-btn" href="<?php echo $this->createUrl('wxbinding/logout'); ?>">
            <i class="o-back-arrow mrm"></i>
            <span>退出当前帐号</span>
        </a>
        <button class="btn fsm wx-suite-install <%= isSuccess ? 'btn-primary' : 'disabled' %>"
                data-action="installApply" <%= isSuccess ? '' : 'disabled' %>>安装套件应用
        </button>
    </div>
</script>
<script src='<?php echo STATICURL; ?>/js/lib/formValidator/formValidator.packaged.js?<?php echo VERHASH; ?>'></script>
<script type="text/javascript" src="<?php echo $this->getAssetUrl(); ?>/js/iboscologin.js"></script>
<script src="<?php echo $assetUrl; ?>/js/syncdata.js"></script>
<script type="text/javascript">
    $(function() {
        var sysurl = '<?php echo $domain; ?>',
            aeskey = '<?php echo $aeskey; ?>',
            access_url = 'https://www.ibos.com.cn/api/api/jsonpCheckAccess?domain=' + encodeURI(sysurl) +
                            '&aeskey=' + aeskey,
            getAccess;

        getAccess = function(data) {
            var $tpl = $.template('access_tpl', data);
            $('.wx-access-panel').append($tpl);

            return true;
        };

        $.ajax({
            type: "get",
            async: false,
            url: access_url,
            dataType: "jsonp",
            jsonp: "oacallback",
            jsonpCallback:"getAccess",
            success: getAccess,
            error: function(){
                console.error('failed to connect');
            }
        });
    })
</script>

system/modules/dashboard/views/wxbinding/login.php
<?php

use application\core\utils\Ibos;
use application\modules\dashboard\utils\Wx;

?>
<link href="<?php echo $this->getAssetUrl(); ?>/css/weixin.css" type="text/css" rel="stylesheet">
<div>
    <div class="ct">
        <div class="clearfix">
            <h1 class="mt"><?php echo $lang['Binding wechat and install now']; ?></h1>
        </div>
        <div>
            <!-- 企业信息 start -->
            <div class="ctb">
                <h2 class="st"><?php echo $lang['Wechat binding'] ?></h2>
                <!--已绑定-->
                <?php if ($isBinding) : ?>
                    <div class="box-shadow bind-info-wrap">
                        <div class="clearfix">
                            <div class="box-shadow ibos-qy">
                                <div class="aes-key" data-toggle="tooltip" data-html="true"
                                     title="<div class='aes-key-tip'><p class='xwb'>AES KEY：</p><p><?php //echo $aeskey; ?></p></div>">
                                    AES KEY
                                </div>
                                <div class="company-logo mbs">
                                    <img src="<?php echo !empty($logo) ? $logo : 'static/image/logo.png'; ?>"
                                         alt="<?php echo $shortname; ?>">
                                    <div class="ibos-logo">
                                        <i class="o-binding-ibos"></i>
                                    </div>
                                </div>
                                <p class="lhl t"><?php echo $fullname; ?></p>
                                <p class="lhl"><?php echo $domain; ?></p>
                            </div>
                            <div class="box-shadow weixin-qy">
                                <div class="company-logo mbs">
                                    <img src="<?php echo $wxlogo; ?>" alt="<?php echo $wxname; ?>">
                                    <div class="weixin-logo">
                                        <i class="o-binding-weixin"></i>
                                    </div>
                                </div>
                                <p class="lhl"><?php echo $wxname; ?></p>
                                <p class="lhl">CorpID : <?php echo $wxcorpid; ?></p>
                            </div>
                            <div class="co-binding-state" data-toggle="tooltip" title="解绑需要到微信企业号后台取消套件托管">
                                <div class="co-binding-icon">
                                    <i class="o-binding-success"></i>
                                    <span></span>绑定成功
                                </div>
                                <div class="co-unbinding-icon"
                                     onclick="window.open('http://doc.ibos.com.cn/article/detail/id/329' ,'_blank');">
                                    <i class="o-unbinding-success"></i>
                                    <span></span>解除绑定
                                </div>
                            </div>
                        </div>
                        <div class="co-binding-login">
                            <p>登录酷办公管理</p>
                            <div class="span11 ml">
                                <input type="text" class="mb" value="<?php echo $mobile; ?>" id="bind_mobile"
                                       placeholder="请输入帐号" autocomplete="off" readonly disabled/>
                                <input type="password" class="mb" id="bind_password" placeholder="请输入密码"/>
                                <button type="button" class="btn btn-primary span12 mb" data-action="loginCorp">登录
                                </button>
                                <div>
                                    <a href="http://www.ibos.com.cn/forgotpass" target="_blank"
                                       class="pull-left">忘记密码?</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--未绑定-->
                <?php else : ?>
                    <div class="co-banding-wrap">
                        <div class="co-binding-info">
                            <div class="box-shadow ibosoa-info clearfix">
                                <div class="company-logo mbs pull-left">
                                    <img src="<?php echo !empty($logo) ? $logo : 'static/image/logo.png'; ?>"
                                         alt="<?php echo $shortname; ?>">
                                    <div class="ibos-logo">
                                        <i class="o-binding-ibos"></i>
                                    </div>
                                </div>
                                <div class="company-info pull-left">
                                    <p class="lhl t"><?php echo $fullname; ?></p>
                                    <p class="lhl">系统URL : <?php echo $domain; ?></p>
                                    <p class="lhl ellipsis"
                                       title="AES KEY : 9Pcz3VcUe6kh-GEAgU3vL99rHUk5F7C-libcteUhQkYC72D8qf">AES KEY
                                        : <?php echo $aeskey; ?></p>
                                </div>
                            </div>
                            <div>
                                <i class="o-unbinding-wxintro"></i>
                            </div>
                            <div class="co-binding-tip">
                                <p class="co-binding-tips">绑定流程</p>
                                <i class="o-binding-wxtip"></i>
                            </div>
                            <div class="co-binding-info-box">
                                <button type="button" class="btn btn-primary binding-btn-wrap mls"
                                        data-action="bindLoginCo">登录酷办公
                                </button>
                                <button type="button" class="btn binding-btn-wrap mls" data-action="bindIbosCo">注册酷办公
                                </button>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<div id="ibosco_register_dialog" style="display:none;">
    <div style="width:300px">
        <form class="form-horizontal" id="ibosco_register_form">
            <div class="user-reg-info" id="user_reg_verify">
                <div class="clearfix mb">
                    <div class="span11 ml12 xac">
                        <h3 class="xwb">欢迎注册酷办公</h3>
                    </div>
                </div>
                <div class="clearfix mb">
                    <div class="pull-left span11 ml12">
                        <input type="text" id="inputMobile" placeholder="手机号" autocomplete="off">
                    </div>
                </div>
                <div class="clearfix mb">
                    <div class="pull-left span11 ml12">
                        <div class="input-group">
                            <input type="text" id="inputMobileVerify" placeholder="短信验证码" autocomplete="off">
                            <span class="input-group-addon pl pr" data-action="getMobileVerifyCode"
                                  data-loading-text="重新发送（<span id='mobile_counting'>60</span>）">获取验证码</span>
                        </div>
                        <div class="xcr">
                            <span id='send_mobile_status'></span>
                        </div>
                    </div>
                </div>
                <div class="clearfix mb">
                    <div class="pull-left span11 ml12">
                        <button type="button" class="btn btn-warning span12" id="next_reg_state"
                                data-evtname="nextState">注册
                        </button>
                    </div>
                </div>
                <div class="clearfix mb">
                    <div class="pull-left span11 ml12">
                        <p class="pull-left">已有帐号？<a href="javascript:;" class="xcbu" data-action="bindLoginCo">立即登录</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="user-reg-info" id="user_reg_info" style="display:none;">
                <div class="clearfix mb">
                    <div class="span11 ml12 xac">
                        <h3 class="xwb">完善个人信息</h3>
                    </div>
                </div>
                <div class="clearfix mb">
                    <div class="pull-left span11 ml12">
                        <input type="text" id="user_name" placeholder="真实姓名" autocomplete="off"/>
                    </div>
                </div>
                <div class="clearfix mb">
                    <div class="pull-left span11 ml12">
                        <input type="password" id="user_password" placeholder="设置登录密码" autocomplete="off"/>
                    </div>
                </div>
                <div class="clearfix mb">
                    <div class="pull-left span11 ml12">
                        <input type="text" id="user_invite" placeholder="邀请人手机号，选填" autocomplete="off"/>
                    </div>
                </div>
                <div class="clearfix mb">
                    <div class="pull-left span11 ml12">
                        <button type="button" class="btn btn-primary span12" id="reg_and_bind"
                                data-evtname="registerCo">完成
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div id="ibosco_login_dialog" style="display:none;">
    <div style="width:300px">
        <form class="form-horizontal" id="ibosco_login_form">
            <div class="clearfix mb">
                <div class="span11 ml12 xac">
                    <h3 class="xwb">欢迎登录酷办公</h3>
                </div>
            </div>
            <div class="clearfix mb">
                <div class="pull-left span11 ml12">
                    <input type="text" id="mobile" placeholder="手机号"/>
                </div>
            </div>
            <div class="clearfix mb">
                <div class="pull-left span11 ml12">
                    <input type="password" id="password" placeholder="密码">
                </div>
            </div>
            <div class="clearfix mb">
                <div class="pull-left span11 ml12">
                    <button type="button" class="btn btn-primary span12" id="login_and_bind" data-evtname="loginCo">登录
                    </button>
                </div>
            </div>
            <div class="clearfix mb">
                <div class="pull-left span11 ml12">
                    <a href="javascript:;" onclick="javascript:window.open('https://www.ibos.cn/forgotpass');"
                       class="pull-left">忘记密码</a>
                    <a href="javascript:;" class="pull-right" data-action="bindIbosCo">免费注册</a>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    Ibos.app.s('page', 'wxbind');
</script>
<script src='<?php echo STATICURL; ?>/js/lib/formValidator/formValidator.packaged.js?<?php echo VERHASH; ?>'></script>
<script type="text/javascript" src="<?php echo $this->getAssetUrl(); ?>/js/iboscologin.js"></script>
<script src="<?php echo $assetUrl; ?>/js/syncdata.js"></script>