system/modules/dashboard/controllers/CreditController.php
<?php

namespace application\modules\dashboard\controllers;

use application\core\utils\Env;
use application\core\utils\Ibos;
use application\core\utils\Cache;
use application\modules\main\model\Setting;
use application\modules\dashboard\model\Credit;
use application\modules\dashboard\model\CreditRule;
use application\modules\dashboard\utils\Dashboard as DashboardUtil;

class CreditController extends BaseController
{

    const MAX_RULE_ID = 5; // 积分允许的最大规则数
    const AUTO_INCREMENT_MAX = 5;
    const AUTO_INCREMENT_MIN = 4;

    /**
     * 积分设置
     * @return void
     */
    public function actionSetup()
    {
        $operation = Env::getRequest('op');
        if (!empty($operation) && in_array($operation, array('add', 'del'))) {
            $method = $operation . 'Credit';
            if (method_exists($this, $method)) {
                return $this->$method();
            }
        }
        $formSubmit = Env::submitCheck('creditSetupSubmit');
        if ($formSubmit) {
            // 积分变动提示
            $changeRemind = isset($_POST['changeRemind']) ? 1 : 0;
            Setting::model()->updateSettingValueByKey('creditremind', $changeRemind);
            // 积分条目
            $credits = $_POST['credit'];
            //统计积分条目个数
            $creditamount = count($credits);
            foreach ($credits as $cid => $credit) {
                if (isset($credit['enable'])) {
                    $credit['enable'] = 1;
                } else {
                    $credit['enable'] = 0;
                }
                if ($credit["name"] == "") {
                    unset($credits[$cid]);
                    continue;
                } else {
                    $credit['name'] = \CHtml::encode($credit['name']);
                }
                $result = Credit::model()->findAllByPk($cid);
                if (!empty($result)) {
                    Credit::model()->modify($cid, $credit);
                } else {
                    Credit::model()->add($credit);
                }
            }
            $removeId = $_POST["removeId"];
            if (!empty($removeId)) {
                //删除数据
                Credit::model()->remove($removeId);
                /* 统计删除积分条目个数
                 * 2015-08-17 14:13  sam
                 */
                $removeArray = explode(',', ltrim($removeId, ','));
                $count = count($removeArray);
                if ($count == 1) {
                    if (in_array(self::AUTO_INCREMENT_MIN, $removeArray) && $creditamount == 3) {
                        Credit::model()->alterAutoIncrementValue(self::AUTO_INCREMENT_MIN);
                    } elseif (in_array(self::AUTO_INCREMENT_MIN, $removeArray) && $creditamount == 4) {
                        //原来有5条数据，删除id为4那条数据，则修改id为5的那条数据的id值变为4
                        Credit::model()->modify(self::AUTO_INCREMENT_MAX, array('cid' => self::AUTO_INCREMENT_MIN));
                        //更新主键自增值为5
                        Credit::model()->alterAutoIncrementValue(self::AUTO_INCREMENT_MAX);
                    } elseif (in_array(self::AUTO_INCREMENT_MAX, $removeArray)) {
                        //更新主键自增值为5
                        Credit::model()->alterAutoIncrementValue(self::AUTO_INCREMENT_MAX);
                    }
                } elseif ($count == 2) {
                    //删除两条数据更新主键自增值为4
                    Credit::model()->alterAutoIncrementValue(self::AUTO_INCREMENT_MIN);
                }
            }
            Cache::update(array('setting'));
            $this->success(Ibos::lang('Save succeed', 'message'));
        } else {
            $credits = Credit::model()->fetchAll();
            $data = array(
                // 积分数据
                'data' => $credits,
                // 当前积分条目最大数
                'curentMaxId' => Credit::model()->getMaxId('cid'),
                // 允许的积分条目最大数
                'maxId' => self::MAX_RULE_ID,
                // 积分变动提示
                'changeRemind' => Ibos::app()->setting->get('setting/creditremind')
            );
            $this->render('setup', $data);
        }
    }

    /**
     * 积分公式
     */
    public function actionFormula()
    {
        $formSubmit = Env::submitCheck('creditSetupSubmit');
        if ($formSubmit) {
            // 积分公式
            $formula = $_POST['creditsFormula'];
            $formulaCheckCorrect = DashboardUtil::checkFormulaCredits($formula);
            if ($formulaCheckCorrect) {
                Setting::model()->updateSettingValueByKey('creditsformula', $formula);
            } else {
                $this->error(Ibos::lang('Credits formula invalid'));
            }
            // 积分表达式
            $formulaExp = $_POST['creditsFormulaExp'];
            if (trim($formulaExp) == "") {
                $this->success(Ibos::lang('Save succeed', 'message'));
                return;
            }
            Setting::model()->updateSettingValueByKey('creditsformulaexp', $formulaExp);
            Cache::update(array('setting'));
            $this->success(Ibos::lang('Save succeed', 'message'));
        } else {
            $credits = Credit::model()->fetchAll();
            $data = array(
                // 积分数据
                'data' => $credits,
                // 积分公式
                'creditsFormula' => Setting::model()->fetchSettingValueByKey('creditsformula'),
                // 积分表达式
                'creditFormulaExp' => Setting::model()->fetchSettingValueByKey('creditsformulaexp')
            );
            $this->render('formula', $data);
        }
    }

    /**
     * 积分策略
     * @return void
     */
    public function actionRule()
    {
        $formSubmit = Env::submitCheck('creditRuleSubmit');
        if ($formSubmit) {
            // 接收表单，共三个部分
            $cycles = $_POST['cycles'];
            $credits = $_POST['credits'];
            $rewardNums = $_POST['rewardnums'];
            // 处理更新条件
            $rulesParam = array();
            // 奖励周期
            foreach ($cycles as $ruleId => $cycle) {
                $rulesParam[$ruleId]['cycletype'] = $cycle;
            }
            // 奖励积分
            foreach ($credits as $ruleId => $credit) {
                foreach ($credit as $extcreditOffset => $creditValue) {
                    $rulesParam[$ruleId]['extcredits' . $extcreditOffset] = $creditValue;
                }
            }
            // 奖励次数
            foreach ($rewardNums as $ruleId => $rewardNum) {
                $rulesParam[$ruleId]['rewardnum'] = $rewardNum;
            }
            // 更新
            foreach ($rulesParam as $ruleId => $updateValue) {
                CreditRule::model()->modify($ruleId, $updateValue);
            }
            $this->success(Ibos::lang('Save succeed', 'message'));
        } else {
            $rules = CreditRule::model()->fetchAll();
            $credits = Credit::model()->fetchAll();
            $data = array(
                'rules' => $rules,
                'credits' => $credits,
            );
            $this->render('rule', $data);
        }
    }

    /**
     * 扩展积分添加
     * @return void
     */
    private function addCredit()
    {
        if (Ibos::app()->getRequest()->getIsAjaxRequest()) {
            $attributes = array(
                'name' => Env::getRequest('name'),
                'initial' => Env::getRequest('initial'),
                'lower' => Env::getRequest('lower'),
                'enable' => Env::getRequest('enable')
            );
            $newId = Credit::model()->add($attributes, true);
            if ($newId) {
                $return = array('id' => $newId, 'IsSuccess' => true);
                $this->ajaxReturn($return);
            }
        }
    }

    /**
     * 删除扩展积分
     * @return void
     */
    private function actiondelCredit()
    {
        if (Ibos::app()->getRequest()->getIsAjaxRequest()) {
            $id = Env::getRequest('id');
            $affected = Credit::model()->deleteByPk($id);
            if ($affected) {
                $this->ajaxReturn(array('IsSuccess' => true, 'msg' => Ibos::lang('Delete credit success')));
            } else {
                $this->ajaxReturn(array('IsSuccess' => false, 'msg' => Ibos::lang('Delete credit failed')));
            }
        }
    }

}

system/modules/dashboard/views/credit/formula.php
<div class="ct">
    <div class="clearfix">
        <h1 class="mt"><?php echo $lang['Integral set']; ?></h1>
        <ul class="mn">
            <li>
                <a href="<?php echo $this->createUrl('credit/setup'); ?>"><?php echo $lang['Expand credit']; ?></a>
            </li>
            <li>
                <span><?php echo $lang['Credit formula']; ?></span>
            </li>
            <li>
                <a href="<?php echo $this->createUrl('credit/rule'); ?>"><?php echo $lang['Credit rule']; ?></a>
            </li>
        </ul>
    </div>
    <form action="<?php echo $this->createUrl('credit/formula'); ?>" method="post" class="form-horizontal">
        <div>
            <!-- 总积分计算公式 start -->
            <div class="ctb">
                <h2 class="st"><?php echo $lang['Total credit formula']; ?></h2>
                <div>
                    <div class="ptc radius" id="calculator">
                        <div class="ptcs radius" data-component="display" id="calculator_screen">
                            <?php echo $creditFormulaExp; ?>
                        </div>
                        <input type="hidden" name="creditsFormula" value="<?php echo $creditsFormula; ?>"
                               id="calculator_input">
                        <input type="hidden" name="creditsFormulaExp" value="" id="calculator_expression">
                        <div class="clearfix">
                            <div class="pull-left" data-component="panel">
                                <ul id="credit_type" class="ptctl clearfix">
                                    <?php foreach ($data as $val): ?>
                                        <li><a href="javascript:;" data-id="<?php echo $val['cid']; ?>"
                                               data-type="entry"
                                               data-value="extcredits<?php echo $val['cid']; ?>"><?php echo $val['name']; ?></a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <div class="pull-right" data-component="keyboard">
                                <table class="ptckl">
                                    <tr>
                                        <td colspan="2"><a href="javascript:;" class="ptckl-col2 ptckl-back"
                                                           data-type="action" title="后退" data-value="back"></a></td>
                                        <td><a href="javascript:;" class="ptckl-clear" data-type="action"
                                               data-value="clear" title="清空"></a></td>
                                        <td><a href="javascript:;" class="ptckl-operator" data-type="operator"
                                               data-value="divide">÷</a></td>
                                    </tr>
                                    <tr>
                                        <td><a href="javascript:;" data-type="number" data-value="7">7</a></td>
                                        <td><a href="javascript:;" data-type="number" data-value="8">8</a></td>
                                        <td><a href="javascript:;" data-type="number" data-value="9">9</a></td>
                                        <td><a href="javascript:;" class="ptckl-operator" data-type="operator"
                                               data-value="multiply">×</a></td>
                                    </tr>
                                    <tr>
                                        <td><a href="javascript:;" data-type="number" data-value="4">4</a></td>
                                        <td><a href="javascript:;" data-type="number" data-value="5">5</a></td>
                                        <td><a href="javascript:;" data-type="number" data-value="6">6</a></td>
                                        <td><a href="javascript:;" class="ptckl-operator" data-type="operator"
                                               data-value="minus">-</a></td>
                                    </tr>
                                    <tr>
                                        <td><a href="javascript:;" data-type="number" data-value="1">1</a></td>
                                        <td><a href="javascript:;" data-type="number" data-value="2">2</a></td>
                                        <td><a href="javascript:;" data-type="number" data-value="3">3</a></td>
                                        <td rowspan="2"><a href="javascript:;" class="ptckl-operator ptckl-row2"
                                                           data-type="operator" data-value="plus">+</a></td>
                                    </tr>
                                    <tr>
                                        <td colspan="2"><a href="javascript:;" class="ptckl-col2" data-type="number"
                                                           data-value="0">0</a></td>
                                        <td><a href="javascript:;" class="ptckl-operator" data-type="bracket"
                                               data-value="(">()</a></td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <button class="btn btn-primary btn-large btn-submit" name="creditSetupSubmit" value="1"
                    type="submit"><?php echo $lang['Submit'] ?></button>
        </div>
    </form>
</div>
<script src="<?php echo $assetUrl; ?>/js/db_credit_fomula.js"></script>

system/modules/dashboard/views/credit/rule.php
<div class="ct">
    <div class="clearfix">
        <h1 class="mt"><?php echo $lang['Integral set']; ?></h1>
        <ul class="mn">
            <li>
                <a href="<?php echo $this->createUrl('credit/setup'); ?>"><?php echo $lang['Expand credit']; ?></a>
            </li>
            <li>
                <a href="<?php echo $this->createUrl('credit/formula'); ?>"><?php echo $lang['Credit formula']; ?></a>
            </li>
            <li>
                <span><?php echo $lang['Credit rule']; ?></span>
            </li>
        </ul>
    </div>
    <div>
        <!-- 积分策略 start -->
        <div class="ctb">
            <h2 class="st"><?php echo $lang['Credit rule']; ?></h2>
            <div class="alert trick-tip clearfix">
                <div class="trick-tip-title">
                    <strong><?php echo $lang['Skills prompt']; ?></strong>
                </div>
                <p class="trick-tip-content">
                    <?php echo $lang['Credit rule tips']; ?>
                </p>
            </div>
            <form action="<?php echo $this->createUrl('credit/rule'); ?>" method="post" class="form-horizontal">
                <table class="table table-bordered table-striped table-operate">
                    <!-- Todo :: fixed layer，跟随显示表头效果-->
                    <thead>
                    <tr>
                        <th><?php echo $lang['Rule name']; ?></th>
                        <th width="100"><?php echo $lang['Cycle']; ?></th>
                        <th width="100"><?php echo $lang['Cycle reward nums']; ?></th>
                        <?php foreach ($credits as $credit) : ?>
                            <th width="60"><?php echo $credit['name']; ?></th>
                        <?php endforeach; ?>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($rules as $rule) : ?>
                        <tr>
                            <td><?php echo $rule['rulename']; ?></td>
                            <td>
                                <select data-type="cycletype" data-value="<?php echo $rule['rid']; ?>"
                                        name="cycles[<?php echo $rule['rid']; ?>]" class="input-small">
                                    <option value="1"
                                            <?php if ($rule['cycletype'] == '1'): ?>selected<?php endif; ?>><?php echo $lang['Once']; ?></option>
                                    <option value="2"
                                            <?php if ($rule['cycletype'] == '2'): ?>selected<?php endif; ?>><?php echo $lang['Per hour']; ?></option>
                                    <option value="3"
                                            <?php if ($rule['cycletype'] == '3'): ?>selected<?php endif; ?>><?php echo $lang['Every day']; ?></option>
                                    <option value="4"
                                            <?php if ($rule['cycletype'] == '4'): ?>selected<?php endif; ?>><?php echo $lang['Weekly']; ?></option>
                                    <option value="5"
                                            <?php if ($rule['cycletype'] == '5'): ?>selected<?php endif; ?>><?php echo $lang['Per mensem']; ?></option>
                                </select>
                            </td>
                            <td>
                                <input id="reward_num_<?php echo $rule['rid']; ?>" type="text"
                                       value="<?php echo $rule['rewardnum']; ?>"
                                       name="rewardnums[<?php echo $rule['rid']; ?>]" class="input-small">
                            </td>
                            <?php foreach ($credits as $index => $credit) : ?>
                                <?php $offset = (integer)($index + 1); ?>
                                <td>
                                    <input type="text" value="<?php echo $rule['extcredits' . $offset] ?>" length="4"
                                           name="credits[<?php echo $rule['rid']; ?>][<?php echo $offset; ?>]"
                                           class="input-small">
                                </td>
                            <?php endforeach; ?>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <input type="hidden" name="formhash" value="<?php echo FORMHASH; ?>"/>
                <button name="creditRuleSubmit" class="btn btn-primary btn-large btn-submit"
                        type="submit"><?php echo $lang['Submit']; ?></button>
            </form>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('[data-type="cycletype"]').on('change', function () {
            var val = this.value,
                identifier = $(this).attr('data-value');
            if (val === '1') {
                $('#reward_num_' + identifier).val('').attr('disabled', true);
            } else {
                $('#reward_num_' + identifier).removeAttr('disabled');
            }
        });
        $('[data-type="cycletype"]').change();
    });
</script>

system/modules/dashboard/views/credit/setup.php
<div class="ct">
    <div class="clearfix">
        <h1 class="mt">通用设置 > <?php echo $lang['Integral set']; ?></h1>
        <ul class="mn">
            <li>
                <span><?php echo $lang['Expand credit']; ?></span>
            </li>
            <li>
                <a href="<?php echo $this->createUrl('credit/formula'); ?>"><?php echo $lang['Credit formula']; ?></a>
            </li>
            <li>
                <a href="<?php echo $this->createUrl('credit/rule'); ?>"><?php echo $lang['Credit rule']; ?></a>
            </li>
        </ul>
    </div>
    <form action="<?php echo $this->createUrl('credit/setup'); ?>" method="post" class="form-horizontal">
        <div>
            <!-- 扩展积分设置 start -->
            <div class="ctb">
                <h2 class="st"><?php echo $lang['Expand credit setup']; ?></h2>
                <table class="point-table table table-bordered table-striped table-operate" id="point_setup_table">
                    <thead>
                    <tr>
                        <th><?php echo $lang['Credit name']; ?></th>
                        <th width="60"><?php echo $lang['Initial credit']; ?></th>
                        <th width="60"><?php echo $lang['Credit lower']; ?></th>
                        <th width="80"><?php echo $lang['Credit enable']; ?></th>
                        <th width="40"><?php echo $lang['Operation']; ?></th>
                    </tr>
                    </thead>
                    <tbody id="point_setup_tbody">
                    <?php foreach ($data as $val): ?>
                        <tr id="credit_<?php echo $val['cid']; ?>">
                            <td>
                                <input type="text" class="input-small" name="credit[<?php echo $val['cid']; ?>][name]"
                                       value="<?php echo $val['name']; ?>">
                            </td>
                            <td>
                                <input type="text" class="input-small"
                                       name="credit[<?php echo $val['cid']; ?>][initial]"
                                       value="<?php echo $val['initial']; ?>">
                            </td>
                            <td>
                                <input type="text" class="input-small" name="credit[<?php echo $val['cid']; ?>][lower]"
                                       value="<?php echo $val['lower']; ?>">
                            </td>
                            <td>
                                <input type="checkbox" name="credit[<?php echo $val['cid']; ?>][enable]"
                                       <?php if ($val['enable'] == 1): ?>checked<?php endif; ?> data-toggle="switch"
                                       class="visi-hidden">
                            </td>
                            <td>
                                <?php if ($val['system'] != 1): ?>
                                    <a href="javascript:;" data-action="removeCreditRule"
                                       data-id="<?php echo $val['cid']; ?>" class="cbtn o-trash"
                                       title="<?php echo $lang['Del']; ?>"></a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="4">
                            <a href="javascript:;" data-action="addCreditRule" class="cbtn o-plus"
                               title="<?php echo $lang['Add credit']; ?>"></a>
                        </td>
                        <td hidden>
                            <a href="javascript:;" data-action="resetCreditRule" class="cbtn o-cancel"
                               title="<?php echo $lang['Restore system Settings']; ?>"></a>
                        </td>
                    </tr>
                    </tfoot>
                </table>
                <div>
                    <div class="control-group">
                        <label class="control-label"><?php echo $lang['Credit change remind']; ?></label>
                        <div class="controls">
                            <input type="checkbox" name="changeRemind" data-toggle="switch" class="visi-hidden"
                                   <?php if ($changeRemind): ?>checked<?php endif; ?>>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <input type="hidden" name="removeId" id="removeId"/>
            <button class="btn btn-primary btn-large btn-submit" name="creditSetupSubmit" value="1"
                    type="submit"><?php echo $lang['Submit'] ?></button>
        </div>
        <img id="loading_img" style="display:none;" src='<?php echo STATICURL ?>/image/common/loading.gif'/>
    </form>
</div>
<script type="text/template" id="ext_credit_tpl">
    <tr id="credit_<%= cid %>">
        <td><input type="text" class="input-small" name="credit[<%= cid %>][name]"></td>
        <td><input type="text" class="input-small" name="credit[<%= cid %>][initial]"></td>
        <td><input type="text" class="input-small" name="credit[<%= cid %>][lower]"></td>
        <td><input type="checkbox" data-toggle="switch" class="visi-hidden" name="credit[<%= cid %>][enable]"></td>
        <td><a href="javascript:;" data-action="removeCreditRule" data-id="<%= cid %>" class="cbtn o-trash"
               title="<?php echo $lang['Del']; ?>"></a></td>
    </tr>
</script>
<script>
    Ibos.app.s({
        "maxExtNum": <?php echo $maxId; ?>
    })
</script>
<script src="<?php echo $assetUrl; ?>/js/db_credit_setup.js"></script>