system/modules/dashboard/controllers/OptimizeController.php
<?php

namespace application\modules\dashboard\controllers;

use application\core\utils\Cache;
use application\core\utils\Env;
use application\core\utils\Ibos;
use application\core\utils\StringUtil;
use application\modules\dashboard\controllers\BaseController;
use application\modules\main\model\Setting;

class OptimizeController extends BaseController
{

    const DEFAULT_SEARCH_MODULE = 'email,diary,article'; // 默认支持的全文搜索模块

    /**
     * 性能优化 - 内存设置
     * @return void
     */

    public function actionCache()
    {
        if (LOCAL) {
            $operation = Env::getRequest('op');
            if ($operation == 'clear') {
                Cache::clear();
                $this->success(Ibos::lang('Operation succeed', 'message'));
            }
            $options = Ibos::app()->cache->options;
            $cacheExtension = Ibos::app()->cache->getExtension();
            $cacheType = $options['type'];
            $caches = array();
            foreach ($cacheExtension as $cacheName => $enable) {
                $index = ucfirst($cacheName);
                $caches[$index]['extension'] = (boolean)$enable;
                $caches[$index]['op'] = (strcasecmp($cacheType, $cacheName) === 0);
            }
            $data = array('list' => $caches);
            $this->render('cache', $data);
        } else {
            echo Ibos::lang('Not compatible service', 'message');
        }
    }

    /**
     * 性能优化 - 全文搜索
     * @return void
     */
    public function actionSearch()
    {
        if (LOCAL) {
            // 先取出所有相关记录
            $sphinxFields = 'sphinxon,sphinxmsgindex,sphinxsubindex,sphinxmaxquerytime,sphinxlimit,sphinxrank';
            $sphinx = Setting::model()->fetchSettingValueByKeys($sphinxFields);
            // -----------------
            $formSubmit = Env::submitCheck('searchSubmit');
            if ($formSubmit) {
                $operation = $_POST['operation'];
                // 接收数据
                $data = array(
                    'sphinxon' => isset($_POST['sphinxon'][$operation]) ? 1 : 0,
                    'sphinxsubindex' => \CHtml::encode($_POST['sphinxsubindex'][$operation]),
                    'sphinxmsgindex' => \CHtml::encode($_POST['sphinxmsgindex'][$operation]),
                    'sphinxmaxquerytime' => \CHtml::encode($_POST['sphinxmaxquerytime'][$operation]),
                    'sphinxlimit' => \CHtml::encode($_POST['sphinxlimit'][$operation]),
                    'sphinxrank' => $_POST['sphinxrank'][$operation],
                );
                // 更新相应的$operation选项
                foreach ($sphinx as $sKey => $sValue) {
                    $value = StringUtil::utf8Unserialize($sValue);
                    $value[$operation] = $data[$sKey];
                    Setting::model()->updateSettingValueByKey($sKey, $value);
                }
                Cache::update(array('setting'));
                $this->success(Ibos::lang('Save succeed', 'message'));
            } else {
                $operation = Env::getRequest('op');
                $moduleList = explode(',', self::DEFAULT_SEARCH_MODULE);
                if (!in_array($operation, $moduleList)) {
                    $operation = $moduleList[0];
                }
                $data['operation'] = $operation;
                $data['moduleList'] = $moduleList;
                foreach ($sphinx as $sKey => $sValue) {
                    $data[$sKey] = StringUtil::utf8Unserialize($sValue);
                }
                $this->render('search', $data);
            }
        } else {
            echo Ibos::lang('Not compatible service', 'message');
        }
    }

    /**
     * 性能优化 - Sphinx控制
     * @return void
     */
    public function actionSphinx()
    {
        if (LOCAL) {
            $formSubmit = Env::submitCheck('sphinxSubmit');
            if ($formSubmit) {
                $sphinxHost = \CHtml::encode($_POST['sphinxhost']);
                $sphinxPort = \CHtml::encode($_POST['sphinxport']);
                Setting::model()->updateSettingValueByKey('sphinxhost', $sphinxHost);
                Setting::model()->updateSettingValueByKey('sphinxport', $sphinxPort);
                Cache::update(array('setting'));
                $this->success(Ibos::lang('Save succeed', 'message'));
            } else {
                $record = Setting::model()->fetchSettingValueByKeys('sphinxhost,sphinxport');
                $sphinxPort = Setting::model()->fetchSettingValueByKey('sphinxport');
                $data = array('sphinxHost' => $record['sphinxhost'], 'sphinxPort' => $record['sphinxport']);
                $this->render('sphinx', $data);
            }
        } else {
            echo Ibos::lang('Not compatible service', 'message');
        }
    }

}

system/modules/dashboard/views/optimize/cache.php
<div class="ct">
    <div class="clearfix">
        <h1 class="mt"><?php echo $lang['Performance optimization']; ?></h1>
        <ul class="mn">
            <li>
                <span><?php echo $lang['Optimize Cache']; ?></span>
            </li>
            <!-- <li>
				<a href="<?php echo $this->createUrl('optimize/search'); ?>"><?php echo $lang['Full-text search setup']; ?></a>
			</li>
			<li>
				<a href="<?php echo $this->createUrl('optimize/sphinx'); ?>"><?php echo $lang['Sphnix control']; ?></a>
			</li> -->
        </ul>
    </div>
    <div>
        <!-- 当前内存工作状态 start -->
        <div class="ctb">
            <h2 class="st"><?php echo $lang['Current cache status']; ?></h2>
            <div class="alert trick-tip clearfix">
                <div class="trick-tip-title">
                    <strong><?php echo $lang['Skills prompt']; ?></strong>
                </div>
                <div class="trick-tip-content">
                    <?php echo $lang['Optimize cache tips']; ?>
                </div>
            </div>
            <table class="table table-bordered table-striped table-operate">
                <thead>
                <tr>
                    <th><?php echo $lang['Cache interface']; ?></th>
                    <th width="100"><?php echo $lang['Php environment']; ?></th>
                    <th width="100"><?php echo $lang['Clear cache']; ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $cacheName => $option) : ?>
                    <tr>
                        <td><?php echo $cacheName; ?></td>
                        <td>
                            <?php
                            if ($option['extension']) {
                                echo $lang['Support'];
                            } else {
                                echo $lang['Nonsupport'];
                            }
                            ?>
                        </td>
                        <td>
                            <?php if ($option['op']) : ?>
                                <a href="<?php echo $this->createUrl('optimize/cache', array('op' => 'clear')); ?>"><?php echo $lang['Clear']; ?></a>
                            <?php else: ?>
                                --
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

system/modules/dashboard/views/optimize/search.php
<div class="ct">
    <div class="clearfix">
        <h1 class="mt"><?php echo $lang['Performance optimization']; ?></h1>
        <ul class="mn">
            <li>
                <a href="<?php echo $this->createUrl('optimize/cache'); ?>"><?php echo $lang['Optimize Cache']; ?></a>
            </li>
            <li>
                <span><?php echo $lang['Full-text search setup']; ?></span>
            </li>
            <li>
                <a href="<?php echo $this->createUrl('optimize/sphinx'); ?>"><?php echo $lang['Sphnix control']; ?></a>
            </li>
        </ul>
    </div>
    <div>
        <!-- Sphinx全文检索设置 start -->
        <div class="ctb">
            <h2 class="st">Sphinx<?php echo $lang['Full-text search setup']; ?></h2>
            <div class="ctbw">
                <form action="<?php echo $this->createUrl('optimize/search'); ?>" method="post" class="form-horizontal">
                    <div class="btn-group control-group">
                        <?php foreach ($moduleList as $module): ?>
                            <a href="<?php echo $this->createUrl('optimize/search', array('op' => $module)); ?>"
                               class="btn<?php if ($operation == $module) : ?> active <?php endif; ?>">
                                <?php echo $lang[$module]; ?>
                            </a>
                        <?php endforeach; ?>
                    </div>
                    <div class="control-group">
                        <label class="control-label"><?php echo $lang['Open or not']; ?></label>
                        <div class="controls">
                            <input type="checkbox" name="sphinxon[<?php echo $operation; ?>]" value="1"
                                   <?php if ($sphinxon[$operation] == '1'): ?>checked<?php endif; ?>
                                   data-toggle="switch" class="visi-hidden"/>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label"><?php echo $lang['Sphinx sub index']; ?></label>
                        <div class="controls">
                            <input id='sphinxSubIndex' value="<?php echo $sphinxsubindex[$operation]; ?>" type="text"
                                   name='sphinxsubindex[<?php echo $operation; ?>]'/>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label"><?php echo $lang['Sphinx msg index']; ?></label>
                        <div class="controls">
                            <input id='sphinxMsgIndex' value="<?php echo $sphinxmsgindex[$operation]; ?>" type="text"
                                   name='sphinxmsgindex[<?php echo $operation; ?>]'/>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label"><?php echo $lang['Sphinx max query time']; ?></label>
                        <div class="controls">
                            <input id="sphinxMaxQueryTime" value="<?php echo $sphinxmaxquerytime[$operation]; ?>"
                                   type="text" name="sphinxmaxquerytime[<?php echo $operation; ?>]"/>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label"><?php echo $lang['Sphinx limit']; ?></label>
                        <div class="controls">
                            <input id="sphinxLimit" value="<?php echo $sphinxlimit[$operation]; ?>" type="text"
                                   name="sphinxlimit[<?php echo $operation; ?>]"/>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label"><?php echo $lang['Sphinx rank']; ?></label>
                        <div class="controls">
                            <select id='sphinxRank' name="sphinxrank[<?php echo $operation; ?>]">
                                <option
                                    <?php if ($sphinxrank[$operation] == 'SPH_RANK_PROXIMITY_BM25'): ?>selected<?php endif; ?>
                                    value="SPH_RANK_PROXIMITY_BM25">SPH_RANK_PROXIMITY_BM25
                                </option>
                                <option <?php if ($sphinxrank[$operation] == 'SPH_RANK_BM25'): ?>selected<?php endif; ?>
                                        value="SPH_RANK_BM25">SPH_RANK_BM25
                                </option>
                                <option <?php if ($sphinxrank[$operation] == 'SPH_RANK_NONE'): ?>selected<?php endif; ?>
                                        value="SPH_RANK_NONE">SPH_RANK_NONE
                                </option>
                            </select>
                            <p class="help-block"></p>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label"></label>
                        <div class="controls">
                            <input type="hidden" name="operation" value="<?php echo $operation; ?>"/>
                            <button type="submit" name="searchSubmit"
                                    class="btn btn-primary btn-large btn-submit"><?php echo $lang['Submit']; ?></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $assetUrl; ?>/js/db_optimize.js"></script>

system/modules/dashboard/views/optimize/sphinx.php
<div class="ct">
    <div class="clearfix">
        <h1 class="mt"><?php echo $lang['Performance optimization']; ?></h1>
        <ul class="mn">
            <li>
                <a href="<?php echo $this->createUrl('optimize/cache'); ?>"><?php echo $lang['Optimize Cache']; ?></a>
            </li>
            <li>
                <a href="<?php echo $this->createUrl('optimize/search'); ?>"><?php echo $lang['Full-text search setup']; ?></a>
            </li>
            <li>
                <span><?php echo $lang['Sphnix control']; ?></span>
            </li>
        </ul>
    </div>
    <div>
        <!-- Sphinx控制 start -->
        <div class="ctb">
            <h2 class="st"><?php echo $lang['Sphnix control']; ?></h2>
            <div class="ctbw">
                <form method="post" action="<?php echo $this->createUrl('optimize/sphinx'); ?>" class="form-horizontal">
                    <div class="control-group">
                        <label class="control-label"><?php echo $lang['Sphinx host']; ?></label>
                        <div class="controls">
                            <input type="text" id='sphinxHost' name="sphinxhost" value="<?php echo $sphinxHost; ?>"/>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label"><?php echo $lang['Sphinx port']; ?></label>
                        <div class="controls">
                            <input type="text" id='sphinxPort' name="sphinxport" value="<?php echo $sphinxPort; ?>"/>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label"></label>
                        <div class="controls">
                            <button type="submit" name="sphinxSubmit"
                                    class="btn btn-primary btn-large btn-submit"><?php echo $lang['Submit']; ?></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $assetUrl; ?>/js/db_optimize.js"></script>